name: My github action
on: [push]
jobs:
 build-job:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: ls -la
     - uses: actions/setup-java@v2
     - run: apt-get install maven
     - run: mvn -version
     - run: mvn clean install 
    
