name: My github action
on: [push]
jobs:
 my-firstjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello World !!!"
      - run: echo "Hello!!! @@@@"
 build-job:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: tree
    
