name: My github action
on: [push]
jobs:
 build-job:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     #- run: ls -la
     - uses: actions/setup-java@v2
       with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
     #- run: mvn -version
     - name: build
       run: mvn clean install 
     - name: nexus upload
       env:
         PWD: ${{ secrets.PWD }}
       run: curl -v -u admin:$pwd --upload-file /home/runner/work/Spring-app/Spring-app/target/Spring-app-0.0.1-SNAPSHOT.war http://34.125.147.30:8081/repository/maven-snapshots/com.wipro/spring-app/0.0.1-SNAPSHOT/spring-app-0.0.1-SNAPSHOT.war
    
